
# YOLO26m Custom: P2 Head + CBAM Attention
# Scale: Medium (m)

# Parameters
nc: 1  
scales: # model compound scaling constants, i.e. 'n', 's', 'm', 'l', 'x'
  # [depth, width, max_channels]
  # n: [0.33, 0.25, 1024] 
  # s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768] 
  # l: [1.00, 1.00, 512]
  # x: [1.00, 1.25, 512]

# Backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]   # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4 (Lấy cho P2)
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8 (Lấy cho P3)
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16 (Lấy cho P4)
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]    # 9
  
  # --- CUSTOM MODULE ---
  - [-1, 1, CBAM, [576]]       # 10. CBAM Attention (Ngay sau SPPF)
  # ---------------------

# Head
head:
  # --- Top-down Path ---
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4 (Layer 6)
  - [-1, 3, C2f, [512]]         # 13

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3 (Layer 4)
  - [-1, 3, C2f, [256]]         # 16

  # [MỞ RỘNG P2 HEAD]
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]  # cat backbone P2 (Layer 2)
  - [-1, 3, C2f, [128]]         # 19 (Output P2 - High Res)

  # --- Bottom-up Path ---
  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 16], 1, Concat, [1]] # cat layer 16
  - [-1, 3, C2f, [256]]         # 22 (Output P3)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]] # cat layer 13
  - [-1, 3, C2f, [512]]         # 25 (Output P4)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]] # cat layer 10 (Output CBAM)
  - [-1, 3, C2f, [1024]]        # 28 (Output P5)

  # --- Detect Head (4 Outputs) ---
  - [[19, 22, 25, 28], 1, Detect, [nc]] 
